// Generated by `bun init`

interface ImportMetaEnv {
  readonly BUN_PUBLIC_ENABLE_PRINT_DEBUG_PANEL?: string;
}

interface ImportMeta {
  readonly env?: ImportMetaEnv;
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
