// Generated by `bun init`

interface ImportMetaEnv {
  /** Set by `scripts/build.ts` for browser bundles; may be absent under `bun --watch` dev. */
  readonly DEV?: boolean;
}

interface ImportMeta {
  readonly env?: ImportMetaEnv;
}

declare module "*.fnt" {
  interface BmFontChar {
    char: string;
    x: number;
    y: number;
    width: number;
    height: number;
    xoffset: number;
    yoffset: number;
    xadvance: number;
  }

  interface BmFontData {
    common: {
      lineHeight: number;
      base: number;
      scaleW: number;
      scaleH: number;
    };
    distanceField: {
      distanceRange: number;
    };
    chars: BmFontChar[];
  }

  const data: BmFontData;
  export default data;
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
